name: "Rust CI"
on:
  pull_request:

jobs:
  build:
    name: cargo build and test
    runs-on: [ubuntu-latest]
    container:
      image: nvidia/cuda:12.2.0-devel-ubuntu22.04
    env:
      BELLMAN_CUDA_DIR: ${{ github.workspace }}/bellman-cuda
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: sudo apt update && sudo apt install -y pkg-config libssl-dev libclang-dev gcc g++ cmake curl
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2022-08-23
          rustflags: ""
      - name: Clone bellman-cuda repository
        uses: actions/checkout@v3
        with:
          repository: matter-labs/era-bellman-cuda
          fetch-depth: 0
          path: ./bellman-cuda
      - name: Build bellman-cuda
        run: |
          cmake -Bbellman-cuda/build -Sbellman-cuda/ -DCMAKE_BUILD_TYPE=Release &&
          cmake --build bellman-cuda/build/

      - run: cargo build --verbose
      - run: cargo test --package api-testing --release --no-run

  formatting:
    name: cargo fmt
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
